### ISSUE TITLE
Error message when running edge-core

### ISSUE THREAD

**Issue by moonchen** [ARMmbed/mbed-edge#7] opened 2018-10-22 22:38 UTC
When running edge-core 0.6.0 on x64 without modifications, I get many errors like the following:

```
2018-10-22 17:33:57.297 tid:  29577 [ERR ][PAL ]: SSL Read return code -30848.
2018-10-22 17:33:57.768 tid:  29577 [ERR ][mClt]: M2MBase::handle_observation() - already auto-observable or missing token!
2018-10-22 17:33:57.980 tid:  29577 [ERR ][mClt]: M2MBase::handle_observation() - already auto-observable or missing token!
2018-10-22 17:33:58.030 tid:  29577 [ERR ][mClt]: M2MBase::handle_observation() - not observable!
2018-10-22 17:33:58.182 tid:  29577 [ERR ][mClt]: M2MBase::handle_observation() - already auto-observable or missing token!
2018-10-22 17:33:58.282 tid:  29577 [ERR ][mClt]: M2MBase::handle_observation() - not observable!
2018-10-22 17:33:58.581 tid:  29577 [ERR ][mClt]: M2MBase::handle_observation() - already auto-observable or missing token!
2018-10-22 17:33:58.631 tid:  29577 [ERR ][mClt]: M2MBase::handle_observation() - not observable!
2018-10-22 17:33:58.780 tid:  29577 [ERR ][mClt]: M2MBase::handle_observation() - already auto-observable or missing token!
2018-10-22 17:33:58.879 tid:  29577 [ERR ][mClt]: M2MBase::handle_observation() - already auto-observable or missing token!
2018-10-22 17:33:59.085 tid:  29577 [ERR ][mClt]: M2MBase::handle_observation() - already auto-observable or missing token!
2018-10-22 17:33:59.138 tid:  29577 [ERR ][mClt]: M2MBase::handle_observation() - not observable!
2018-10-22 17:33:59.253 tid:  29577 [ERR ][mClt]: M2MBase::handle_observation() - already auto-observable or missing token!
2018-10-22 17:33:59.453 tid:  29577 [ERR ][mClt]: M2MBase::handle_observation() - already auto-observable or missing token!
```

A full debug output dump here:
https://gist.github.com/moonchen/db91ac6d862a5aa9eddad8768d7ef539

**Comment by ciarmcom** [comment] 2018-10-23 00:31
ARM Internal Ref: IOTGW-838

**Comment by JanneKiiskila** [comment] 2018-11-05 08:32
Fix proposal in place, to be tested. This is an Cloud side issue, so no change expected to Edge code.

**Comment by jjaakola-arm** [comment] 2019-01-10 08:03
Closing, the issue is resolved.

**Closed by jjaakola-arm** 2019-01-10 08:03 UTC
Labels: mirrored
